pipeline{
    agent { label 'master' }
    
    tools{
        nodejs 'nodejs-v16.18.1'
    }

    stages{
        stage("Git resource from git"){
            steps{
               git 'https://github.com/leangsengk90/seng-react-test.git'
            }
        }
        /*
        stage("Built Project"){
            steps{
                sh 'npm install'
                sh 'npm run build'
            }
        }
        */
        stage("Build Docker Image"){
            steps{
                /*
                withCredentials([usernamePassword(credentialsId: 'dockerhub-auth', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh "docker build -t xeng/kube-reactjs:${BUILD_NUMBER} ."
                    sh "docker login -u ${USERNAME} -p ${PASSWORD}"
                    sh 'docker push xeng/kube-reactjs:${BUILD_NUMBER}'
                }
                sh 'docker logout'
                */
                
                script{
                    docker.withRegistry('', 'dockerhub-auth') {
                        def customImage = docker.build("xeng/kube-reactjs:${BUILD_NUMBER}")
                        /* Push the container to the custom Registry */
                        customImage.push()
                    }
                }
                sh 'docker logout'
            }
        }
     
        stage("Deploy App"){
            steps{
                sshagent(['jenkins-ssh-keys']) {
                    sh 'ls && pwd'
                    sh 'scp -o StrictHostKeyChecking=no -r kubernetes dara@10.148.0.12:/home/dara'
                    sh "ssh -o StrictHostKeyChecking=no dara@10.148.0.12:/home/dara/kubernetes bash deploy.sh ${BUILD_NUMBER}"
                }
            }
        }
        
    }
}
